# Generated by Django 2.2.8 on 2020-01-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
