# Generated by Django 2.2.4 on 2019-10-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
