# Generated by Django 2.2.4 on 2019-10-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_userprofileinfo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
