# Generated by Django 2.2.8 on 2020-01-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200118_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
