# Generated by Django 2.2.4 on 2019-10-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191021_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'replie'},
        ),
    ]
