# Generated by Django 2.2.4 on 2019-08-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190820_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
