# Generated by Django 2.2.4 on 2019-09-22 01:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
