# Generated by Django 2.2.4 on 2019-08-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
