# Generated by Django 2.2.4 on 2019-10-22 12:08

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userprofileinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
