# Generated by Django 2.2.4 on 2019-10-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20191027_1502'),
        ('mainapp', '0010_remove_post_dislikes'),
    ]

    operations = [
    ]
