# Generated by Django 2.2.4 on 2019-10-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_merge_20191028_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
