# Generated by Django 2.2.4 on 2019-10-31 09:27

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_post_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_files', validators=[mainapp.validators.validate_file_extension]),
        ),
    ]
