# Generated by Django 2.2.4 on 2019-11-25 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20191125_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='post_saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
