# Generated by Django 2.2.4 on 2019-11-27 04:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20191125_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(default='default_banner.jpg', upload_to='banner_pics'),
        ),
    ]
